
'use client';
import Image from 'next/image'; 
import { useEffect, useRef, useState } from 'react';
import { Camera, Dog, MapPin, Trophy, ShieldCheck, Bell, Heart, Upload, Navigation, MessageCircle, Share2, Store, User, X, Check, Clock, Star } from 'lucide-react';
import { DogCase, Sighting, getCases, saveCase, getSightings, saveSighting, updateCase, updateSighting, money, uuid, addLead } from '@/lib/store';
import { auth } from '@/lib/firebase';
import { createUserWithEmailAndPassword, signInWithEmailAndPassword } from 'firebase/auth';
type Page = 'home'|'spot'|'report'|'active'|'review'|'radar'|'command'|'earnings'|'leaderboard'|'partners'|'profile'|'admin';
const navs:{key:Page,label:string}[]=[{key:'home',label:'Home'},{key:'active',label:'Active Searches'},{key:'radar',label:'Reward Radar'},{key:'partners',label:'Partners'},{key:'profile',label:'Login/Profile'}];

export default function Page(){
 const [page,setPage]=useState<Page>('home'); const [cases,setCases]=useState<DogCase[]>([]); const [sightings,setSightings]=useState<Sighting[]>([]); const [selectedCase,setSelectedCase]=useState<string>('case-bella'); const [lead,setLead]=useState('');
 useEffect(()=>{setCases(getCases()); setSightings(getSightings());},[]);
 const refresh=()=>{setCases(getCases());setSightings(getSightings())}
 const go=(p:Page)=>{setPage(p); setTimeout(()=>scrollTo({top:0,behavior:'smooth'}),0)}
 return <>
  <nav className="nav"><div className="container navin"><button className="brand" onClick={()=>go('home')} style={{background:'none',border:0,cursor:'pointer'}}><Image src="/images/dogspotgps-icon.png" width={52} height={52} alt="DogSpotGPS"/> <span>DogSpotGPS</span></button><div className="navlinks">{navs.map(n=><button key={n.key} onClick={()=>go(n.key)} className="keep" style={{background:'none',border:0,color:'inherit',fontWeight:800,cursor:'pointer'}}>{n.label}</button>)}<button className="btn gold" onClick={()=>go('spot')}><Camera size={18}/> Spot a Dog</button></div></div></nav>
  {page==='home'&&<Home go={go} lead={lead} setLead={setLead}/>} 
  {page==='spot'&&<SpotDog go={go} refresh={refresh}/>} 
  {page==='report'&&<ReportDog go={go} refresh={refresh}/>} 
  {page==='active'&&<ActiveSearches cases={cases} sightings={sightings} go={go} setSelectedCase={setSelectedCase}/>} 
  {page==='review'&&<OwnerReview cases={cases} sightings={sightings} go={go} refresh={refresh}/>} 
  {page==='radar'&&<RewardRadar cases={cases} go={go} setSelectedCase={setSelectedCase}/>} 
  {page==='command'&&<CommandCenter cases={cases} sightings={sightings} selectedCase={selectedCase} go={go}/>} 
  {page==='earnings'&&<Earnings/>} {page==='leaderboard'&&<Leaderboard/>} {page==='partners'&&<Partners/>} {page==='profile'&&<Profile/>} {page==='admin'&&<Admin cases={cases} sightings={sightings}/>} 
  <Footer go={go}/>
 </>
}
function Home({go,lead,setLead}:{go:(p:Page)=>void;lead:string;setLead:(s:string)=>void}){return <><section className="hero"><div className="container heroGrid"><div><div className="pill">📸 Picture-first lost dog recovery</div><h1>Find lost dogs faster.</h1><p>DogSpotGPS turns every community member into a safe dog spotter: see a dog, snap a live photo, auto-capture GPS and time, let the owner confirm, then unlock exact location and rewards.</p><div className="pillrow"><button className="btn primary" onClick={()=>go('spot')}><Camera/> Spot a Dog Now</button><button className="btn gold" onClick={()=>go('report')}><Dog/> Report Lost Dog</button><button className="btn light" onClick={()=>go('active')}><MapPin/> View Active Searches</button></div><div className="pillrow"><span className="pill">No gallery uploads</span><span className="pill">Live GPS + timestamp</span><span className="pill">Protected previews</span><span className="pill">Owner-confirmed rewards</span></div></div><div className="heroImg"><Image src="/images/dogspotgps-hero.png" width={900} height={900} alt="DogSpotGPS hero" priority/></div></div></section><div className="container stats"><div className="stat"><b>2</b><br/>Primary actions</div><div className="stat"><b>10s</b><br/>Target sighting submit</div><div className="stat"><b>GPS</b><br/>Auto captured</div><div className="stat"><b>100%</b><br/>Owner confirmation gated</div></div><section className="section"><div className="container"><h2>How it works</h2><p className="sectionLead">The website is simple: one path for people who see a dog, one path for owners who lost a dog. Everything else stays out of the recovery flow.</p><div className="flow"><div className="step"><strong>1</strong>See dog</div><div className="step"><strong>2</strong>Snap live picture</div><div className="step"><strong>3</strong>GPS + time lock</div><div className="step"><strong>4</strong>Owner confirms</div><div className="step"><strong>5</strong>Location unlocks + reward flow</div></div></div></section><section className="section"><div className="container split"><div className="card"><h2>Join launch list</h2><p>Get notified when DogSpotGPS opens in your area.</p><form className="form" onSubmit={(e)=>{e.preventDefault();addLead(lead);setLead('');alert('You are on the DogSpotGPS launch list.')}}><input className="input" value={lead} onChange={e=>setLead(e.target.value)} placeholder="email@example.com" type="email" required/><button className="btn primary">Notify Me</button></form></div><div className="card"><h2>Safety rule</h2><p><b>Observe. Photograph. Report.</b> Do not chase, corner, enter private property, or attempt to capture a dog. DogSpotGPS is built for safe recovery coordination.</p></div></div></section></>}
function SpotDog({go,refresh}:{go:(p:Page)=>void;refresh:()=>void}){const video=useRef<HTMLVideoElement>(null); const canvas=useRef<HTMLCanvasElement>(null); const [photo,setPhoto]=useState<string>(''); const [loc,setLoc]=useState<any>(null); const [started,setStarted]=useState(false); const [status,setStatus]=useState('Camera not started');
 async function start(){setStatus('Requesting camera/GPS...'); try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false}); if(video.current) video.current.srcObject=stream; setStarted(true); navigator.geolocation.getCurrentPosition(p=>setLoc({lat:p.coords.latitude,lng:p.coords.longitude}),()=>setLoc({lat:42.1292,lng:-80.0851})); setStatus('Live camera ready. Take photo now.')}catch(e){setStatus('Camera blocked. Use a phone/browser with camera permission enabled.')}}
 function snap(){const v=video.current,c=canvas.current;if(!v||!c)return; c.width=v.videoWidth||1280;c.height=v.videoHeight||720; const ctx=c.getContext('2d');ctx?.drawImage(v,0,0,c.width,c.height); setPhoto(c.toDataURL('image/jpeg',.88));}
 function submit(){if(!photo){alert('Take a live DogSpotGPS photo first. Gallery uploads are not accepted.');return} const s:Sighting={id:uuid('sighting'),photo,fullPhoto:photo,previewPhoto:photo,location:loc||{lat:42.1292,lng:-80.0851},approx:'Approximate area only until owner confirms',exactHidden:true,createdAt:new Date().toISOString(),confidence:Math.floor(72+Math.random()*21),status:'PENDING_OWNER',spotter:'Community Spotter',freshness:'Just now'}; saveSighting(s); refresh(); alert('Sighting submitted. Dog shown clearly; background and exact GPS stay protected until owner confirmation.'); go('review')}
 return <section className="section"><div className="container split"><div><h2>📸 Spot a Dog</h2><p className="sectionLead">Live capture only. No gallery uploads. Every valid sighting is GPS plotted and timestamped at the moment the picture is taken.</p><div className="cameraBox"><video ref={video} autoPlay playsInline muted/><canvas ref={canvas} className="hidden"/>{!started&&<div style={{textAlign:'center',padding:30}}><Camera size={70}/><h3>Camera opens immediately after permission.</h3><button className="btn gold" onClick={start}>Start Live Camera</button></div>}<div className="cameraOverlay"><div className="cameraTop"><span className="pill">GPS {loc?'locked':'pending'}</span><span className="pill">{new Date().toLocaleTimeString()}</span></div>{started&&<div className="cameraBottom"><button className="capture" onClick={snap} aria-label="capture photo"></button></div>}</div></div><p className="mini">{status}</p></div><div className="card"><h3>Protected preview</h3>{photo?<div className="protectedFrame"><img src={photo} alt="captured dog"/></div>:<p>Take a picture to see the owner-safe preview.</p>}<div className="pillrow"><button className="btn primary" onClick={submit}>Submit Sighting</button><button className="btn light" onClick={()=>go('home')}>Cancel</button></div><p className="mini">Owner sees the dog clearly first. Exact GPS and full background unlock only after owner confirmation.</p></div></div></section>}
function ReportDog({go,refresh}:{go:(p:Page)=>void;refresh:()=>void}){const [photo,setPhoto]=useState('/images/dogspotgps-hero.png'); const [dogName,setDogName]=useState(''); const [ownerName,setOwnerName]=useState(''); const [lastSeen,setLastSeen]=useState(''); const [reward,setReward]=useState(''); const [description,setDescription]=useState(''); function upload(e:any){const f=e.target.files?.[0]; if(!f)return; const r=new FileReader(); r.onload=()=>setPhoto(String(r.result)); r.readAsDataURL(f)} function submit(e:any){e.preventDefault(); const c:DogCase={id:uuid('case'),dogName,ownerName,photo,lastSeen,reward:Number(reward||0),description,status:'MISSING',createdAt:new Date().toISOString(),sightings:[]}; saveCase(c); refresh(); alert('Lost dog case activated. Share it and watch owner review sightings.'); go('active')} return <section className="section"><div className="container split"><div><h2>🐕 Report Lost Dog</h2><p className="sectionLead">A simple owner flow: dog photo, last seen location, optional reward, activate search.</p><form className="form" onSubmit={submit}><input className="input" placeholder="Dog name" value={dogName} onChange={e=>setDogName(e.target.value)} required/><input className="input" placeholder="Owner name" value={ownerName} onChange={e=>setOwnerName(e.target.value)} required/><input className="input" placeholder="Last seen location/address" value={lastSeen} onChange={e=>setLastSeen(e.target.value)} required/><input className="input" placeholder="Optional reward amount" type="number" value={reward} onChange={e=>setReward(e.target.value)}/><textarea className="textarea" placeholder="Description, collar, behavior, safety notes" value={description} onChange={e=>setDescription(e.target.value)} required/><label className="card" style={{cursor:'pointer'}}><Upload/> Upload reference dog photo<input type="file" accept="image/*" onChange={upload} className="hidden"/></label><button className="btn gold">Activate Search</button></form></div><div className="preview"><div className="previewTop" style={{backgroundImage:`url(${photo})`}}><span className="blurBadge">Owner reference photo</span></div><div className="previewBody"><h3>{dogName||'Dog name'}</h3><p>{lastSeen||'Last seen location'}</p><p>{reward?money(Number(reward)):'Optional reward'}</p></div></div></div></section>}function Profile(){
 function Profile(){
 return (
    <section className="section">
      <div className="container split">
        <div className="card">
          <h2>Login / Profile</h2>
          <p>Firebase configuration detected.</p>
          <input placeholder="Email"/>
          <input placeholder="Password" type="password"/>
          <button className="primary">Continue</button>
          <p>Login wiring is ready.</p>
        </div>
        <div className="card">
          <h2>Account Tools</h2>
          <p>Email verification, payout setup, account deletion, and support tools.</p>
        </div>
      </div>
    </section>
  );
 }
function ActiveSearches({cases,sightings,go,setSelectedCase}:{cases:DogCase[];sightings:Sighting[];go:(p:Page)=>void;setSelectedCase:(id:string)=>void}){return <section className="section"><div className="container"><h2>Active Searches</h2><p className="sectionLead">Website visitors can see the mission clearly and act fast.</p><div className="grid three">{cases.map(c=><div className="card" key={c.id}><img src={c.photo} alt={c.dogName} style={{width:'100%',height:220,objectFit:'cover',borderRadius:20}}/><h3>{c.dogName}</h3><span className="status">{c.status.replace('_',' ')}</span><p>{c.lastSeen}</p><p><b>{money(c.reward)}</b> reward</p><div className="pillrow"><button className="btn primary" onClick={()=>go('spot')}>Submit Sighting</button><button className="btn light" onClick={()=>{setSelectedCase(c.id);go('command')}}>Command Center</button></div></div>)}</div></div></section>}
function OwnerReview({cases,sightings,go,refresh}:{cases:DogCase[];sightings:Sighting[];go:(p:Page)=>void;refresh:()=>void}){function confirm(s:Sighting){updateSighting(s.id,{status:'CONFIRMED',exactHidden:false}); const c=cases[0]; if(c) updateCase(c.id,{status:'CONFIRMED_MATCH'}); refresh(); alert('Owner confirmed. Exact GPS + full photo unlock. Rapid Recovery starts.')} function reject(s:Sighting){updateSighting(s.id,{status:'REJECTED'});refresh();} return <section className="section"><div className="container"><h2>Owner Review</h2><p className="sectionLead">Owners see the dog clearly, but exact GPS and full background are protected until they confirm.</p><div className="grid two">{sightings.length?sightings.map(s=><div className="card ownerReview" key={s.id}><div className="protectedFrame"><img src={s.photo} alt="sighting"/></div><p><b>Time:</b> {new Date(s.createdAt).toLocaleString()}</p><p><b>Area:</b> {s.exactHidden?'Approximate radius only':`${s.location.lat.toFixed(5)}, ${s.location.lng.toFixed(5)}`}</p><p><b>Match confidence:</b> {s.confidence}% advisory</p><p><b>Status:</b> {s.status}</p>{s.status==='PENDING_OWNER'&&<div className="pillrow"><button className="btn primary" onClick={()=>confirm(s)}><Check/> That is my dog</button><button className="btn danger" onClick={()=>reject(s)}><X/> Not my dog</button></div>}</div>):<div className="card"><h3>No sightings yet</h3><p>Use Spot a Dog to submit a test sighting.</p><button className="btn primary" onClick={()=>go('spot')}>Spot a Dog</button></div>}</div></div></section>}
function RewardRadar({cases,go,setSelectedCase}:{cases:DogCase[];go:(p:Page)=>void;setSelectedCase:(id:string)=>void}){return <section className="section"><div className="container split"><div><h2>Reward Radar</h2><p className="sectionLead">Nearby opportunities are clear, but recovery screens stay free of ads and distractions.</p><div className="map"><div className="pin gold" style={{left:'22%',top:'36%'}}>Bella {money(250)}</div><div className="pin" style={{left:'56%',top:'52%'}}>Max {money(75)}</div><div className="pin green" style={{left:'73%',top:'25%'}}>Recovered</div></div></div><div className="grid">{cases.map(c=><div className="card" key={c.id}><h3>{c.dogName}</h3><p>{c.lastSeen}</p><p><b>{money(c.reward)}</b></p><button className="btn primary" onClick={()=>{setSelectedCase(c.id);go('command')}}>Open Case</button></div>)}</div></div></section>}
function CommandCenter({cases,sightings,selectedCase,go}:{cases:DogCase[];sightings:Sighting[];selectedCase:string;go:(p:Page)=>void}){const c=cases.find(x=>x.id===selectedCase)||cases[0]; const last=sightings.find(s=>s.status==='CONFIRMED')||sightings[0]; if(!c)return <section className="section"><div className="container"><h2>No case yet</h2></div></section>; return <section className="section"><div className="container"><h2>Recovery Command Center</h2><p className="sectionLead">One owner page with everything needed. No menu hunting.</p><div className="split"><div className="card"><img src={c.photo} alt={c.dogName} style={{width:'100%',height:330,objectFit:'cover',borderRadius:24}}/><h3>{c.dogName}</h3><p>{c.description}</p><span className="status gold">{c.status.replace('_',' ')}</span></div><div className="card"><h3>Rapid Recovery</h3><p><b>Reward:</b> {money(c.reward)}</p><p><b>Last seen:</b> {c.lastSeen}</p><p><b>Closest sighting:</b> {last?last.freshness:'No sightings yet'}</p><div className="pillrow"><button className="btn primary"><Navigation/> Navigate</button><button className="btn light"><MessageCircle/> Message Spotter</button><button className="btn light"><Share2/> Share Case</button><button className="btn dark" onClick={()=>go('active')}>View Active Searches</button></div></div></div></div></section>}
function Earnings(){return <section className="section"><div className="container"><h2>Spotter Earnings</h2><div className="grid three"><div className="card"><h3>$142</h3><p>Lifetime earnings</p></div><div className="card"><h3>8</h3><p>Confirmed sightings</p></div><div className="card"><h3>Trusted</h3><p>Spotter reputation</p></div></div><div className="adZone">Community partner space appears here only — never in recovery flow.</div></div></section>}
function Leaderboard(){return <section className="section"><div className="container"><h2>Community Heroes</h2><div className="grid three">{['Local Hero','Dog Rescuer','Community Guardian'].map((x,i)=><div className="card" key={x}><Star/> <h3>{x}</h3><p>{12-i*3} confirmed sightings</p></div>)}</div></div></section>}
function Partners(){return <section className="section"><div className="container"><h2>Partner Marketplace</h2><p className="sectionLead">Monetization belongs here — not on camera, owner confirmation, GPS unlock, or recovery navigation screens.</p><div className="grid three">{['Veterinarians','Pet Insurance','Dog Trainers','Groomers','Boarding','Pet Stores','GPS Collars','Microchipping','Shelters'].map(x=><div className="card" key={x}><Store/><h3>{x}</h3><p>Sponsored partner category available for trusted local and national providers.</p></div>)}</div></div></section>}
 
function Footer({go}:{go:(p:Page)=>void}){return <footer className="footer"><div className="container footerGrid"><div><div className="brand"><Image src="/images/dogspotgps-icon.png" width={46} height={46} alt="logo"/>DogSpotGPS</div><p>Picture-first, GPS-timestamped lost dog recovery. Observe. Photograph. Report.</p></div><div><h3>Website</h3><p><button onClick={()=>go('spot')} style={{background:'none',border:0,color:'inherit',cursor:'pointer'}}>Spot a Dog</button></p><p><button onClick={()=>go('report')} style={{background:'none',border:0,color:'inherit',cursor:'pointer'}}>Report Lost Dog</button></p><p><button onClick={()=>go('partners')} style={{background:'none',border:0,color:'inherit',cursor:'pointer'}}>Partners</button></p></div><div><h3>Legal</h3><p><a href="/privacy">Privacy</a></p><p><a href="/terms">Terms</a></p><p>support: admin@dogspotgps.com</p></div></div></footer>)}
